### ISSUE TITLE
Consider support for rejecting duplicate keys

### ISSUE THREAD

**Issue by lmsurpre** [eclipse-ee4j/jsonp#240]
We like the javax.json API and we're using it to implement a domain-specific integration.

One limitation we've hit is that the implementations use a "last one wins" approach to duplicate keys in JSON.
In our particular use case, we'd like the option to be "strict" and reject a request that has duplicate keys.

Jackson supports this type of behavior through a special Feature:
https://fasterxml.github.io/jackson-core/javadoc/2.9/com/fasterxml/jackson/core/JsonParser.Feature.html#STRICT_DUPLICATE_DETECTION

Would the maintainers of this reference implementation entertain a Pull Request to add a similar capability which could be enabled when passed via a config property to the `Json.createReaderFactory(config)` factory method?

**Comment by jjspiegel** [comment]
This seems like a reasonable request.  One could imagine a duplicate keys handling option that accepts something like USE_FIRST, USE_LAST, REJECT

**Comment by m0mus** [comment]
It doesn't affect the API, so PR is welcome. It can be targeted to the next release.

**Comment by JohnTimm** [comment]
Since `JsonParserImpl` uses a `JsonObjectBuilderImpl` under the covers:

https://github.com/eclipse-ee4j/jsonp/blob/master/impl/src/main/java/org/glassfish/json/JsonParserImpl.java#L309-L320

We may be able to reject duplicate keys in a specialization of `JsonObjectBuilderImpl`. However, this may violate the contract in the `JsonObjectBuilder` interface:

> If the object contains a mapping for the specified name, this method replaces the old value with the specified value.

**Comment by JohnTimm** [comment]
A potential "quick" fix would be to make `putValueMap` protected and then throw an exception if `valueMap.put(key, value)` returns a non-null value (indicating there was a previous mapping). The only thing I haven't figured out is how to make that configurable. I guess the builder creation from the parser might be the place. This solution would only work with JsonReader I would also need to look into how it could be implemented for the streaming parser (which seems like a heavier lift).

**Comment by JohnTimm** [comment]
@m0mus Added a PR for this issue. Please have a look.

**Comment by lukasj** [comment]
fixed through #241

**Comment by rmannibucau** [comment]
Hi,

Is this intended to be portable, FYI Apache Johnzon added support for that in its reader and builder factories (guess it is the only relevant places to support it since parser is user driven and writer is limited by map contract already).
We added it using johnzon.rejectDuplicateKeys but we also support org.glassfish.json.rejectDuplicateKeys but I'd like it to be jakarta.json.rejectDuplicateKeys instead (with true/false/<missing> values in the map config of the related factories - default being false).

**Comment by lukasj** [comment]
>  I'd like it to be jakarta.json.rejectDuplicateKeys instead

that would be a spec change which has not been allowed to be done in 2.0.x

**Comment by rmannibucau** [comment]
@lukasj does not prevent to spec it for 2.1, 2.0 is done since no change is allowed  as you mentionned so spec can branch 2.0 for maintenance and let eclipse community can work on 2.1.

**Comment by lukasj** [comment]
@rmannibucau 

> does not prevent to spec it for 2.1

feel free to file new issue followed by the PR, nobody is preventing anyone from doing so. Mixing various things on one place makes no sense to me - this issue is/was for the implementation, not for the API/spec.

>  2.0 is done

2.0.1 is not done yet. It has not been approved by spec committee for release. Neither is the plan for 2.1 - basically because EE 9.1 is not done yet.
